export const items = [
  {
    id: 1,
    title: "Upcoming Show Live from Paris",
    subtitle: "SPRING-SUMMER 2021",
    picture: require("./assets/chanel.jpg"),
    top: 0,
  },
  {
    id: 2,
    title: "Deauville Film Festival",
    subtitle: "CHANEL IN CINEMA",
    picture: require("./assets/laura-chouette-NFrPPyGe5q0-unsplash-with-gradient.jpg"),
    top: 0,
  },
  {
    id: 3,
    title: "Haute Couture",
    subtitle: "FALL-WINTER 2020/21",
    picture: require("./assets/khaled-ghareeb-upepKTbwm3A-unsplash.jpg"),
    top: 50,
  },
  {
    id: 4,
    title: "Spring-Summer 2020 Campaign",
    subtitle: "EYEWEAR",
    picture: require("./assets/chase-fade-Pb13EUxzMDw-unsplash.jpg"),
    top: 0,
  },
  {
    id: 5,
    title: "Upcoming Show Live from Paris",
    subtitle: "SPRING-SUMMER 2021",
    picture: require("./assets/chanel.jpg"),
    top: 0,
  },
  {
    id: 6,
    title: "Deauville Film Festival",
    subtitle: "CHANEL IN CINEMA",
    picture: require("./assets/laura-chouette-NFrPPyGe5q0-unsplash-with-gradient.jpg"),
    top: 0,
  },
  {
    id: 7,
    title: "Haute Couture",
    subtitle: "FALL-WINTER 2020/21",
    picture: require("./assets/khaled-ghareeb-upepKTbwm3A-unsplash.jpg"),
    top: 50,
  },
  {
    id: 8,
    title: "Spring-Summer 2020 Campaign",
    subtitle: "EYEWEAR",
    picture: require("./assets/chase-fade-Pb13EUxzMDw-unsplash.jpg"),
    top: 0,
  },
  {
    id: 9,
    title: "Upcoming Show Live from Paris",
    subtitle: "SPRING-SUMMER 2021",
    picture: require("./assets/chanel.jpg"),
    top: 0,
  },
];
